### PR TITLE
first unittests

### PR DESCRIPTION
**Pull request by nagimov**
I've decided to go with my favorite `ddt` module for these tests (it allows catching individual failed cases within the same test).
Some stuff fails right now, but I'm not sure that I understand the module (and cron itself) good enough, so maybe those test cases are wrong. I've incorporated most of the old tests cases and added some new stuff in here.
I need some help with periodic triggers here (everything I tried failed). Some stuff might have to be pepified as well (sorry)

### CODE REVIEW

**Comment by ericpruitt** [comment]
The date from the first commit says is May 25th, but I only got a notification for your comment. Did you open this pull request earlier and I just overlooked it? I skimmed the commit, but it'll probably be about a week and half before I dedicate some time to reviewing it in depth, looking into the ddt module since I have not used it before and moving this project off the back burner again.

**Comment by nagimov** [comment]
I've committed on May but forgot to pull-request it (doh)
Whenever you have time, and let me know if I can help any more
Thanks!

**Comment by ericpruitt** [comment]
The minimum Python version supported by the ddt test library is Python 2.7, and I want Cronex to support 2.6. I would prefer to have the unit test functions run through all test cases if one non-critical test fails. I will try to do this by deriving a custom unit test class from the one provided by the standard library, but if I can't create an interface I like, I may use ddt anyway since the suite doesn't **need** to be run by Cronex's users since the tests for the rewritten module will no longer rely on the host's clock.

**Comment by ericpruitt** [comment]
I made a wrapper for the standard library's unittest.TestCase that adds support for non-fatal exceptions for all "assert..." and "test..." methods along with a context manager to defer exception reporting for arbitrary statements. I just pushed the code to the rewrite branch: https://github.com/ericpruitt/cronex/blob/rewrite/cronex/unittest.py . Assertion failures are deferred with `fatal=False` -- the default. If there are any other features from ddt that you think might be worth re-implementing, let me know. Otherwise, I'll close this pull request.

**Pull request closed without merging**
